# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
it:
   languageCode: it
   contentDir: content/it
   title: HomePage di Claudio Stazzone
   params:
     description: HomePage di Claudio Stazzone
   menu:
     main:
       - name: Articoli
         url: '#posts'
         weight: 20
             
       - name: Progetti
         url: '#projects'
         weight: 30

       - name: Contatti
         url: '#contact'
         weight: 60
